//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace T871027
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountStatement
    {
        public int Id { get; set; }
        public string GeneralEntryCode { get; set; }
        public string EntryCode { get; set; }
        public Nullable<System.DateTime> TheDate { get; set; }
        public Nullable<int> EmployeeId { get; set; }
        public Nullable<decimal> Debit { get; set; }
        public Nullable<decimal> Credit { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> ExchangeRate { get; set; }
        public Nullable<int> OperationId { get; set; }
        public Nullable<int> TheMonth { get; set; }
        public Nullable<int> TheYear { get; set; }
        public string Details { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string PcNameWhoAdded { get; set; }
        public string PcNameWhoModified { get; set; }
        public string PcNameWhoDeleted { get; set; }
        public string UserWhoAdded { get; set; }
        public string UserWhoModified { get; set; }
        public string UserWhoDeleted { get; set; }
        public Nullable<decimal> ForeignDebitVoucherAmount { get; set; }
        public Nullable<decimal> ForeignCreditVoucherAmount { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Operation Operation { get; set; }


    }
}
