//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace T871027
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.AccountStatement = new HashSet<AccountStatement>();
            this.EmployeeAttachments = new HashSet<EmployeeAttachments>();
            this.FixedOperation = new HashSet<FixedOperation>();
            this.Voucher = new HashSet<Voucher>();
        }
    
        public int Id { get; set; }
        public string EmployeeCode { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<decimal> BasicSalary { get; set; }
        public string IdNumber { get; set; }
        public Nullable<System.DateTime> BirthOfDate { get; set; }
        public Nullable<int> ChildrenNumber { get; set; }
        public string Department { get; set; }
        public string EducationLevel { get; set; }
        public string EmployeeType { get; set; }
        public string Gender { get; set; }
        public string MaritalStatus { get; set; }
        public string MobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string Speciality { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public string Address { get; set; }
        public Nullable<bool> IsCivilEmployee { get; set; }
        public string EmployerJob { get; set; }
        public Nullable<decimal> CivilSalary { get; set; }
        public byte[] EmployeeImage { get; set; }
        public Nullable<decimal> OpeningNis { get; set; }
        public Nullable<decimal> OpeningUsd { get; set; }
        public Nullable<bool> IsActive { get; set; }

    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AccountStatement> AccountStatement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmployeeAttachments> EmployeeAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FixedOperation> FixedOperation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Voucher> Voucher { get; set; }
    }
}
