//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace T871027
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedOperation
    {
        public int Id { get; set; }
        public int EmployeeId { get; set; }
        public int OperationId { get; set; }
        public decimal Amount { get; set; }
        public int CurrencyId { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Operation Operation { get; set; }
    }
}
