//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace T871027
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public int Id { get; set; }
        public string VoucherCode { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime TheDate { get; set; }
        public int OperationId { get; set; }
        public decimal VoucherAmount { get; set; }
        public int CurrencyId { get; set; }
        public decimal ExchangeRate { get; set; }
        public Nullable<decimal> ForeignVoucherAmount { get; set; }
        public string Details { get; set; }
        public string PcNameWhoAdded { get; set; }
        public string PcNameWhoModified { get; set; }
        public string PcNameWhoDeleted { get; set; }
        public string UserWhoAdded { get; set; }
        public string UserWhoModified { get; set; }
        public string UserWhoDeleted { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsFixed { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Operation Operation { get; set; }


    }
}
